import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="w-[23.438rem] h-[50.75rem] m-auto border-[1px] border-solid border-black">
        {/* Status Bar */}
        <div className="w-100vw h-[2.75rem] border-[1px] border-solid border-blue">
          Status Bar
        </div>
        {children}
      </body>
    </html>
  );
}
